# Site settings
title: Design Portfolio
email: robinfoxin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring web designer and developer, specialising in Jekyll, HTML, CSS, and Javascript
baseurl: "/jekyll-portfolio" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: smugfox
github_username:  smugfox
google_username:  smugfox

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
